queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>0"
      - label=automerge
    merge_conditions:
      - or:
          - base~=cosmos/
          - base~=chains/

    commit_message_template: >
      {{ title }} (#{{ number }})

      {{ body }}
    merge_method: squash

pull_request_rules:
  - name: automerge with label automerge and branch protection passing
    conditions: []
    actions:
      queue:
