services:
  cleanup:
    # this is for dev only. cleanup and restart quickly.
    # not done within setup to prevent conflict with running postgres image.
    # use postgres and not alpine because rm is available in both.
    image: postgres:15
    container_name: bdjuno-cleanup
    command: >
      sh -c '
      if [ "${RESET_DB}" = "true" ]; then
        echo "RESET_DB is true. Cleaning up db_data...";
        find /var/lib/postgresql/data -mindepth 1 -delete;
        chmod 700 /var/lib/postgresql/data;
      else
        echo "RESET_DB is false. Skipping cleanup.";
      fi'
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      RESET_DB: "${RESET_DB:-false}"

  db:
    image: postgres:15
    container_name: bdjuno-db
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-changeme}"
      # set up a default database, which is not used further.
      # apparently this helps to avoid some issues with the postgres image
      POSTGRES_DB: "${POSTGRES_DB:-postgresdb}"
      UID: "${UID:-1000}"
      GID: "${GID:-1000}"
    depends_on:
      cleanup:
        condition: service_completed_successfully
    volumes:
      - ./db_data:/var/lib/postgresql/data

  setup:
    image: postgres:15
    container_name: bdjuno-setup
    depends_on:
      db:
        condition: service_started
    volumes:
      # Mount the folder that has all your .sql files
      - ./database/schema:/schema
    environment:
      # User and password for bdjuno DB
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-changeme}"
      BDJUNO_USER: "${BDJUNO_USER:-bdjuno}"
      BDJUNO_PASSWORD: "${BDJUNO_PASSWORD:-changeme}"
      POSTGRES_DB: "${POSTGRES_DB:-postgresdb}"
      UID: "${UID:-1000}"
      GID: "${GID:-1000}"
      # will only do something if RESET_DB is true
      RESET_DB: "${RESET_DB:-false}"
    entrypoint: ["/bin/bash", "/schema/setup-entrypoint.sh"]

  hasura:
    image: hasura/graphql-engine:v2.0.4
    container_name: bdjuno-hasura
    ports:
      - "8080:8080"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${BDJUNO_USER:-bdjuno}:${BDJUNO_PASSWORD:-changeme}@db:5432/bdjuno
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://${BDJUNO_USER:-bdjuno}:${BDJUNO_PASSWORD:-changeme}@db:5432/bdjuno
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura/migrations
      HASURA_GRAPHQL_METADATA_DIR: /hasura/metadata
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
      HASURA_GRAPHQL_ADMIN_SECRET: "secret"
    volumes:
      - ./hasura:/hasura
    depends_on:
      setup:
        condition: service_completed_successfully

  hasura-cli:
    image: ubuntu:22.04
    container_name: bdjuno-hasura-cli
    volumes:
      - ./hasura:/hasura
    environment:
      HASURA_GRAPHQL_ENDPOINT: http://hasura:8080
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
      HASURA_GRAPHQL_ADMIN_SECRET: "secret"
      RESET_METADATA: "${RESET_METADATA:-false}"
      ACTION_BASE_URL: "http://localhost:8080"
    depends_on:
      - hasura
    entrypoint: ["/bin/bash", "/hasura/metadata-entrypoint.sh"]
